trigger:
  - switch_azure

pool:
  vmImage: 'windows-latest'

jobs:
  - job: tests
    displayName: Run tests

    steps:
    - task: Maven@3
      displayName: 'Run tests'
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '11'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'clean test -Dprofile=local -P !run-migration'
